# Generated by Django 3.1.7 on 2021-04-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_auto_20210426_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='c01Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250, null=True)),
                ('observation', models.CharField(max_length=500, null=True)),
                ('initial_date', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.b02address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.b01clients')),
            ],
        ),
    ]
