# Generated by Django 3.1.7 on 2021-04-04 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a01MethodsRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='a03IsolationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='a05NumberOfChargedConductors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('circuit_esqueme', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='a08UndergroundCorrection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thermal_resistivity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('correction_factory', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='a09GroupingCorrection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('circuit_number', models.IntegerField()),
                ('reference_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a01methodsref')),
            ],
        ),
        migrations.CreateModel(
            name='a08GroupingForms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('reference_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a01methodsref')),
            ],
        ),
        migrations.CreateModel(
            name='a07TemperatureCorrection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('temperature', models.IntegerField()),
                ('isolation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a03isolationtype')),
            ],
        ),
        migrations.CreateModel(
            name='a06CurrentCapacity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nominal_section', models.DecimalField(decimal_places=4, max_digits=12)),
                ('number_of_charged_conductors', models.IntegerField()),
                ('cable_type', models.CharField(max_length=20)),
                ('capacity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('isolation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a03isolationtype')),
                ('reference_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a01methodsref')),
            ],
        ),
        migrations.CreateModel(
            name='a04TemperatureConductors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_temperature', models.IntegerField()),
                ('overload_temperature', models.IntegerField()),
                ('short_circuit_temperature', models.IntegerField()),
                ('isolation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a03isolationtype')),
            ],
        ),
        migrations.CreateModel(
            name='a02MethodsInst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('maximum_diameter', models.IntegerField(default=0)),
                ('cable_type', models.CharField(max_length=10, null=True)),
                ('reference_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a01methodsref')),
            ],
        ),
    ]
