# Generated by Django 3.1.7 on 2021-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210405_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a01methodsref',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='a02methodsinst',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='a02methodsinst',
            name='maximum_diameter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='a03isolationtype',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='a04numberofchargedconductors',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='a05currentcapacity',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='a06temperaturecorrection',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='a07undergroundcorrection',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='a08groupingforms',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='a09groupingcorrection',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
