# Generated by Django 3.1.7 on 2021-04-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_a06temperaturecorrection_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a09groupingcorrection',
            name='reference_method',
        ),
        migrations.AddField(
            model_name='a09groupingcorrection',
            name='factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='a09groupingcorrection',
            name='group_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.a08groupingforms'),
        ),
    ]
