# Generated by Django 3.1.7 on 2021-04-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210406_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='a10State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='a11City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=40)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a10state')),
            ],
        ),
        migrations.CreateModel(
            name='a12District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a11city')),
            ],
        ),
    ]
