# Generated by Django 3.1.7 on 2021-04-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_a10state_a11city_a12district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a12district',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
