# Generated by Django 3.1.7 on 2021-04-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_a10state_a11city_a12district'),
    ]

    operations = [
        migrations.CreateModel(
            name='b01Clients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('treatment', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=300)),
                ('cnpj', models.CharField(max_length=14)),
                ('description', models.CharField(max_length=300)),
                ('fone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='b02Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.b01clients')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.a12district')),
            ],
        ),
    ]
