# Generated by Django 3.1.7 on 2021-04-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b02address',
            name='complement',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='b02address',
            name='street',
            field=models.CharField(max_length=200),
        ),
    ]
